export const darkTheme = {
    mode: "dark",
    PRIMARY_BACKGROUND_COLOR: '#121619',
    PRIMARY_TEXT_COLOR: '#cccccc',
    PRIMARY_BUTTON_COLOR: '#E79E4F',
    PRIMARY_HEADER_COLOR: '#1f2428',
    PRIMARY_CONTAINER_BACKGROUND_COLOR: '#2d3c42',
    PRIMARY_BORDER_COLOR: '#E79E4F',
    PRIMARY_BORDER_INPUT_COLOR: '#E79E4F',
}

export const lightTheme = {
    mode: "light",
    PRIMARY_HEADER_COLOR: '#924444',
    PRIMARY_BACKGROUND_COLOR: '#eadcc1',
    PRIMARY_TEXT_COLOR: '#363636',
    PRIMARY_BUTTON_COLOR: '#924444',
    PRIMARY_CONTAINER_BACKGROUND_COLOR: '#FAF3DD',
    PRIMARY_BORDER_COLOR: '#924444',
    PRIMARY_BORDER_INPUT_COLOR: '#924444',
}

export const yellowTheme = {
    mode: "light",
    PRIMARY_HEADER_COLOR: '#f1c40f',
    PRIMARY_BACKGROUND_COLOR: '#f2f2f2',
    PRIMARY_TEXT_COLOR: '#363636',
    PRIMARY_BUTTON_COLOR: '#f1c40f',
    PRIMARY_CONTAINER_BACKGROUND_COLOR: 'white',
    PRIMARY_BORDER_COLOR: '#f1c40f',
    PRIMARY_BORDER_INPUT_COLOR: '#f1c40f',
}

//#DB7093